app/routes.py
from io import BytesIO
import os
from functools import wraps

from flask import Blueprint, request, render_template, redirect, session, flash, send_file, url_for
from dotenv import load_dotenv
import pandas as pd
from docx import Document

from . import db
from .clientes import Cliente
from .pdf import gerar_pdf
from .mail import enviar_email

main = Blueprint('main', __name__, template_folder=os.path.join(os.path.dirname(__file__), '..', 'templates'))

def login_required(f):
    @wraps(f) 
    def decorated_function(*args, **kwargs):
        # Verificação mais robusta da sessão
        if not session.get('logged_in', False):
            # Armazenar URL solicitada para redirecionamento após login
            session['next_url'] = request.url
            flash('Você precisa fazer login primeiro', 'warning')
            return redirect(url_for('main.login'))
        return f(*args, **kwargs)
    return decorated_function

@main.route('/')
def index():
    return redirect(url_for('main.login'))

@main.route("/login", methods=['GET', 'POST'])
def login():
    # Se já estiver logado, redirecione para o dashboard
    if session.get('logged_in', False):
        return redirect(url_for('main.dashboard'))
        
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        load_dotenv()

        if username == os.getenv('USER') and password == os.getenv('PASSWORD'):
            # Definir a sessão de forma explícita
            session['logged_in'] = True
            session['username'] = username
            
            # Verificar se há uma URL para redirecionamento
            next_url = session.pop('next_url', None)
            
            flash('Login efetuado com sucesso!', 'success')
            if next_url:
                return redirect(next_url)
            return redirect(url_for('main.dashboard'))
        else:
            flash('Usuário ou senha inválidos', 'danger')
    
    return render_template('login.html')

@main.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html')

@main.route('/logout')
def logout():
    # Remover itens específicos da sessão ao invés de limpar tudo
    session.pop('logged_in', None)
    session.pop('username', None)
    flash('Você saiu da conta!', 'info')
    return redirect(url_for('main.login'))

@main.route('/contrato', methods=['GET'])
@login_required
def contrato():
    return render_template('contrato.html')

def substituir_texto_em_documento(doc, substitutos):
    """
    Substitui texto em um documento Word, lidando com texto dividido entre múltiplos runs
    """
    # Para cada parágrafo no documento
    for paragrafo in doc.paragraphs:
        # Para cada chave e valor no dicionário de substituições
        for chave, valor in substitutos.items():
            # Se a chave estiver no texto do parágrafo
            if chave in paragrafo.text:
                texto_inline = paragrafo.text
                texto_inline = texto_inline.replace(chave, valor)
                
                # Limpar todos os runs existentes e adicionar um novo com o texto substituído
                for i in range(len(paragrafo.runs)):
                    paragrafo.runs[0]._element.getparent().remove(paragrafo.runs[0]._element)
                
                run = paragrafo.add_run(texto_inline)
                # Nota: isso remove a formatação original

    # Também verificar tabelas
    for tabela in doc.tables:
        for linha in tabela.rows:
            for celula in linha.cells:
                for paragrafo in celula.paragraphs:
                    for chave, valor in substitutos.items():
                        if chave in paragrafo.text:
                            texto_inline = paragrafo.text
                            texto_inline = texto_inline.replace(chave, valor)
                            
                            for i in range(len(paragrafo.runs)):
                                paragrafo.runs[0]._element.getparent().remove(paragrafo.runs[0]._element)
                            
                            run = paragrafo.add_run(texto_inline)
    
@main.route('/contrato', methods=['POST'])
@login_required
def gerar_contrato():
    if not session.get('logged_in'):
        flash('Você precisa fazer login para gerar contratos', 'warning')
        return redirect(url_for('main.login'))
    
    nome = request.form.get('nome', '')
    cpf = request.form.get('cpf', '')
    servico = request.form.get('servico', '')
    valor = request.form.get('valor', '')
    endereco = request.form.get('endereco', '')
    data = request.form.get('data', '')
    
    caminho_modelo = os.path.join(os.getcwd(), "static", "doc", "contrato_modelo.docx")
    
    # Verificar se o arquivo existe
    if not os.path.exists(caminho_modelo):
        flash(f'Arquivo de modelo não encontrado em: {caminho_modelo}', 'danger')
        return redirect(url_for('main.contrato'))
    
    try:
        doc = Document(caminho_modelo)
        
        substitutos = {
            "{nome}": nome,
            "{cpf}": cpf,
            "{servico}": servico,
            "{valor}": valor,
            "{endereco}": endereco,
            "{data}": data
        }

        substituir_texto_em_documento(doc, substitutos)

        output = BytesIO()
        doc.save(output)
        output.seek(0)
        nome_arquivo = f"contrato_{nome.replace(' ', '_')}.docx"
        
        return send_file(
            output,
            as_attachment=True,
            download_name=nome_arquivo,
            mimetype="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        )
        
    except Exception as e:
        flash(f'Erro ao gerar contrato: {str(e)}', 'danger')
        return redirect(url_for('main.contrato'))

@main.route('/register', methods=['GET'])
@login_required
def show_register_form():
    return render_template('register.html')

@main.route('/register', methods=['POST'])
@login_required
def register():
    try:
        nome = request.form['nome']
        email = request.form['email']
        telefone = request.form['telefone']
        endereco = request.form['endereco']
        valor_servico = float(request.form['service_value'])
        descricao_servico = request.form['service_description']

        novo_cliente = Cliente(
            nome=nome, 
            email=email, 
            telefone=telefone, 
            valor_servico=valor_servico, 
            descricao_servico=descricao_servico, 
            endereco=endereco
        )

        db.session.add(novo_cliente)
        db.session.commit()

        # Gerar PDF e enviar email
        pdf_buffer = gerar_pdf(novo_cliente)
        enviar_email(novo_cliente, pdf_buffer)
        
        flash('Cliente cadastrado e e-mail enviado!', 'success')
        return redirect(url_for('main.listar_clientes'))
    except Exception as e:
        db.session.rollback()
        flash(f'Erro ao cadastrar cliente: {str(e)}', 'danger')
        return redirect(url_for('main.show_register_form'))

@main.route('/clientes')
@login_required
def listar_clientes():
    clientes = Cliente.query.all()
    return render_template('clientes.html', clientes=clientes)

@main.route('/exportar')
@login_required
def exportar():
    try:
        clientes = Cliente.query.all()
        clientes_lista = [{
            'Nome': cliente.nome,
            'Email': cliente.email,
            'Telefone': cliente.telefone,
            'Descrição do Serviço': cliente.descricao_servico,
            'Valor do Serviço': cliente.valor_servico,
            'Endereço': cliente.endereco
        } for cliente in clientes]

        df = pd.DataFrame(clientes_lista)
        output = BytesIO()
        
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            df.to_excel(writer, index=False)
        
        output.seek(0)
        
        return send_file(
            output, 
            download_name='clientes.xlsx', 
            as_attachment=True, 
            mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
    except Exception as e:
        flash(f'Erro ao exportar dados: {str(e)}', 'danger')
        return redirect(url_for('main.listar_clientes'))
    
@main.route('/excluir_cliente/<int:id>', methods=['POST'])
@login_required
def excluir_cliente(id):
    try:
        cliente = Cliente.query.get_or_404(id)
        db.session.delete(cliente)
        db.session.commit()
        flash('Cliente excluído com sucesso!', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Erro ao excluir cliente: {str(e)}', 'danger')
    
    return redirect(url_for('main.listar_clientes'))
    

templates/clientes.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title>Cadastro de Clientes</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #51ace9;
            color: #333;
            line-height: 1.6;
            padding: 20px;
        }

        header {
            text-align: center;
            margin-bottom: 20px;
        }

        h1 {
            color: #ffffff;
        }

        nav {
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
        }

        nav ul {
            list-style: none;
            padding: 0;
        }

        nav ul li {
            display: inline;
            margin-right: 15px;
        }

        nav ul li a {
            text-decoration: none;
            color: #ffffff;
            font-weight: bold;
        }

        nav ul li a:hover {
            text-decoration: underline;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background-color: #fff;
        }

        th,
        td {
            padding: 10px;
            text-align: left;
            border: 1px solid #ccc;
        }

        th {
            background-color: #110ca0;
            color: white;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #e0e0e0;
        }

        tbody tr td {
            color: #333;
        }


        button {
            background-color: #110ca0;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }

        .btn-full {
            width: 100%;
        }

        .btn-excluir {
            background-color: #f44336;
            color: white;
            padding: 5px 10px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        .btn-excluir:hover {
            background-color: #d32f2f;
        }

        .btn-group {
            display: flex;
            gap: 10px;
            margin-top: 20px;
        }

        .modal {
            display: none;
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgba(0, 0, 0, 0.4);
        }

        .modal-content {
            background-color: #fefefe;
            margin: 15% auto;
            padding: 20px;
            border: 1px solid #888;
            width: 300px;
            border-radius: 5px;
            text-align: center;
        }

        .modal-buttons {
            display: flex;
            justify-content: space-between;
            margin-top: 20px;
        }

        .modal-btn {
            padding: 8px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        .confirm-btn {
            background-color: #f44336;
            color: white;
        }

        .cancel-btn {
            background-color: #ccc;
            color: black;
        }
    </style>

</head>

<body>
    <header>
        <h1>Clientes Cadastrados</h1>
    </header>

    <nav>
        <ul>
            <li><a href="{{ url_for('main.register') }}">Voltar para Cadastro</a></li>
        </ul>
        <ul>
            <li><a href="{{ url_for('main.dashboard') }}">Voltar ao Menu Principal</a></li>
        </ul>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <table border="1">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Valor do Serviço</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in clientes %}
            <tr id="cliente-{{ cliente.id }}">
                <td>{{ cliente.nome }}</td>
                <td>{{ cliente.email }}</td>
                <td>{{ cliente.telefone }}</td>
                <td>R$ {{ cliente.valor_servico }}</td>
                <td>
                    <form action="{{ url_for('main.excluir_cliente', id=cliente.id) }}" method="POST"
                        class="delete-form">
                        <button type="button" class="btn-excluir"
                            onclick="confirmarExclusao('{{ cliente.id }}')">Excluir</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="btn-group">
        <a href="{{ url_for('main.exportar') }}">
            <button>Exportar para Excel</button>
        </a>
        <a href="{{ url_for('main.dashboard') }}">
            <button>Voltar ao Menu</button>
        </a>
    </div>

    <div id="modalConfirmacao" class="modal">
        <div class="modal-content">
            <p>Tem certeza que deseja excluir este cliente?</p>
            <div class="modal-buttons">
                <button id="btnConfirmar" class="modal-btn confirm-btn">Confirmar</button>
                <button id="btnCancelar" class="modal-btn cancel-btn">Cancelar</button>
            </div>
        </div>
    </div>

    <script>

        let clienteIdParaExcluir;

        const modal = document.getElementById('modalConfirmacao');
        const btnConfirmar = document.getElementById('btnConfirmar');
        const btnCancelar = document.getElementById('btnCancelar');

        function confirmarExclusao(clienteId) {
            clienteIdParaExcluir = clienteId;
            modal.style.display = 'block';
        }

        btnConfirmar.addEventListener('click', function () {

            const form = document.createElement('form');
            form.method = 'POST';
            form.action = `/excluir_cliente/${clienteIdParaExcluir}`;
            document.body.appendChild(form);
            form.submit();
        });

        btnCancelar.addEventListener('click', function () {
            modal.style.display = 'none';
        });

        window.addEventListener('click', function (event) {
            if (event.target == modal) {
                modal.style.display = 'none';
            }
        });
    </script>
</body>

</html>

templates/contrato.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Clientes</title>

    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #51ace9;
            color: #333;
            line-height: 1.6;
            padding: 20px;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
            color: #ffffff;
        }

        nav {
            margin-bottom: 20px;
        }

        nav ul {
            list-style: none;
            padding: 0;
        }

        nav ul li {
            display: inline;
            margin-right: 15px;
        }

        nav ul li a {
            text-decoration: none;
            color: #4c4faf;
            font-weight: bold;
        }

        nav ul li a:hover {
            text-decoration: underline;
        }

        form {
            background: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 5px 2px 10px 1px rgb(10, 10, 9);
            max-width: 600px;
            margin: 0 auto;
        }

        form p {
            margin-bottom: 15px;
        }

        form label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }

        form input[type="text"],
        form input[type="email"],
        form input[type="tel"],
        form input[type="number"],
        form textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        form input[type="text"]:focus,
        form input[type="email"]:focus,
        form input[type="tel"]:focus,
        form input[type="number"]:focus,
        form textarea:focus {
            border-color: #110ca0;
            outline: none;
        }

        form button {
            background-color: #110ca0;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }

        form button:hover {
            background-color: #45a049;
        }

        button {
            background-color: #110ca0;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
        }

        .btn-group {
            max-width: 900px;
            margin: 0 auto;
            padding-bottom: 20px;
        }
    </style>

</head>

<body>
    <h1>Cadastro de Freelancers</h1>

    <div class="btn-group">
        <a href="{{ url_for('main.dashboard') }}">
            <button>Voltar ao Menu</button>
        </a>
    </div>

    <form action="{{ url_for('main.gerar_contrato') }}" method="post">
        <p><label>Nome: <input type="text" id="nome" autofocus name="nome" required></label></p>
        <p><label>CPF: <input type="" id="cpf" name="cpf" required pattern="\d{3}\.\d{3}\.\d{3}-\d{2}"
                    placeholder="xxx.xxx.xxx-xx" required></label></p>
        <p><label>Serviço: <input type="text" id="servico" name="servico" placeholder="Salgadeira, Monitor (...)"
                    required></label></p>
        <p><label>Valor á pagar (R$):
                <input type="number" id="service_value" name="service_value" step="1.00" min="0" required>
            </label></p>
        <p><label>Endereço: <input type="text" id="endereco" name="endereco" required></label></p>
        <p><label>Data: <input type="date" id="data" autofocus name="data" required></label></p>

        <button type="submit">Gerar contrato</button>
    </form>

</body>

</html>

templates/dashboard.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #51ace9;
            color: #333;
            line-height: 1.6;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            padding: 20px;
        }

        .logo {
            display: block;
            margin: 0 auto 20px;
            width: 50%;
            max-width: 200px;
        }

        main {
            padding: 20px;
            background-color: lightgray;
            border-radius: 5px;
            box-shadow: 5px 2px 10px 1px rgb(10, 10, 9);
        }

        img {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 20%;
        }

        h2 {
            text-align: center;
            margin-bottom: 10px;
            color: rgb(18, 35, 110);
            font-size: 40px;
        }

        p {
            color: #000000;
            text-align: center;
            margin-bottom: 20px;
        }

        a {
            display: inline-block;
            margin: 5px 10px;
            text-decoration: none;
            color: #4CAF50;
            font-weight: bold;
        }

        a:hover {
            text-decoration: underline;
        }

        .success {
            color: green;
        }

        .error {
            color: red;
        }

        button {
            background-color: #2b5eaa;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
        }

        button:hover {
            background-color: #181086;
        }
    </style>
</head>

<body>

    <main>
        <img class="logo" src="/static/images/logo_png.png" alt="Logo Vila do Sol">
        <h2>Bem-vindo!</h2>
        <p>Escolha as seguintes opções:</p>

        <div class="btn-group">
            <a href="{{ url_for('main.register')}}">
                <button>Cadastro de Clientes</button></a>
            <a href="{{ url_for('main.contrato')}}">
                <button>Contrato Prestação de Serviço</button></a>
            <a href="{{ url_for('main.logout') }}">
                <button>Sair</button></a>
        </div>
    </main>

</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Cadastro Cliente</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #51ace9;
            color: #333;
            line-height: 1.6;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            padding: 20px;
        }

        .logo {
            display: block;
            margin: 0 auto 20px;
            width: 50%;
            max-width: 200px;
        }

        .container {
            text-align: center;
            background-color: lightgray;
            box-shadow: 2px 2px 5px black;
            padding: 20px;
            border-radius: 5px;
            max-width: 400px;
            width: 100%;
        }

        h2 {
            margin-bottom: 10px;
            color: #181086;
        }

        p {
            margin-bottom: 20px;
        }

        form {
            background: lightgray;
            padding: 20px;
            border-radius: 5px;
            max-width: 400px;
            width: 100%;
            margin: 0 auto;
        }

        form input[type="text"],
        form input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        form input[type="text"]:focus,
        form input[type="password"]:focus {
            border-color: #181086;
            outline: none;
        }

        form button {
            background-color: #2a6fa8;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            width: 100%;
        }

        form button:hover {
            background-color: #2a6fa8;
        }
    </style>
</head>

<body>

    <div class="container">

        <img class="logo" src="/static/images/logo_png.png" alt="Logo Vila do Sol">
        <p>Informe seu usuário e senha para acessar o sistema</p>
        <form method="POST">
            <input type="text" name="username" placeholder="Usuário" required>
            <input type="password" name="password" placeholder="Senha" required>
            <button type="submit">Entrar</button>
        </form>
    </div>
</body>

</html>

templates/register.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Clientes</title>

    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #51ace9;
            color: #333;
            line-height: 1.6;
            padding: 20px;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
            color: #ffffff;
        }

        nav {
            margin-bottom: 20px;
        }

        nav ul {
            list-style: none;
            padding: 0;
        }

        nav ul li {
            display: inline;
            margin-right: 15px;
        }

        nav ul li a {
            text-decoration: none;
            color: #4c4faf;
            font-weight: bold;
        }

        nav ul li a:hover {
            text-decoration: underline;
        }

        form {
            background: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 5px 2px 10px 1px rgb(10, 10, 9);
            max-width: 600px;
            margin: 0 auto;
        }

        form p {
            margin-bottom: 15px;
        }

        form label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }

        form input[type="text"],
        form input[type="email"],
        form input[type="tel"],
        form input[type="number"],
        form textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        form input[type="text"]:focus,
        form input[type="email"]:focus,
        form input[type="tel"]:focus,
        form input[type="number"]:focus,
        form textarea:focus {
            border-color: #110ca0;
            outline: none;
        }

        form button {
            background-color: #110ca0;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }

        form button:hover {
            background-color: #45a049;
        }

        button {
            background-color: #110ca0;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
        }

        .btn-clients {
            padding-top: 5px;
            max-width: 900px;
            margin: 0 auto;
            display: grid;
            place-items: center;
        }
        .btn-dash {
            padding-top: 5px;
            max-width: 900px;
            margin: 0 auto;
            display: grid;
            place-items: center;
        }
    </style>

</head>

<body>
    <h1>Cadastro de Clientes</h1>

    <form action="{{ url_for('main.register') }}" method="post">
        <p><label>Nome: <input type="text" id="nome" autofocus name="nome" required></label></p>
        <p><label>E-mail: <input type="email" id="email" name="email" placeholder="exemplo@mail.com" required></label>
        </p>
        <p><label>Telefone: <input type="tel" id="telefone" name="telefone" required></label></p>
        <p><label>Endereço: <input type="text" id="endereco" name="endereco" required></label></p>
        <p><label>CPF: <input type="" id="cpf" name="cpf" required pattern="\d{3}\.\d{3}\.\d{3}-\d{2}"
                    placeholder="xxx.xxx.xxx-xx" required></label></p>

        <p><label>Valor do Serviço (R$):
                <input type="number" id="service_value" name="service_value" step="1.00" min="0" required>
            </label></p>

        <p><label>Descrição do Serviço:</label></p>
        <textarea id="service_description" name="service_description" rows="4" cols="50" required></textarea>

        <button type="submit">Cadastrar</button>
    </form>


    <div class="btn-clients">
        <a href="{{ url_for('main.listar_clientes') }}">
            <button>Ver Lista de Clientes Cadastrados</button>
        </a>

    </div>
    <div class="btn-dash">
        <a href="{{ url_for('main.dashboard') }}">
            <button>Voltar ao Menu Principal</button>
        </a>
    </div>
</body>

</html>